Web/Boxty.Web/Controllers/CategoryController.cs
namespace Boxty.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Boxty.Data;
    using Boxty.Data.Models;
    using Boxty.Services.Interfaces;
    using Boxty.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [Authorize(Roles = "manager,admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View(this.categoryService.GetAllCategories<CategoryViewModel>());
        }

        public IActionResult Details(int id)
        {
            var category = categoryService.GetCategoryById(id);
            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Category category)
        {
            if (!ModelState.IsValid)
            {
                return this.View(category);
            }

            try
            {
                await categoryService.CreateCategory(category.Name);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(category);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await categoryService.DeleteCategory(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Boxty.Web/Controllers/OrderController.cs
namespace Boxty.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Boxty.Common;
    using Boxty.Data.Models;
    using Boxty.Services.Data.Interfaces;
    using Boxty.Services.Interfaces;
    using Microsoft.AspNetCore.Mvc;

    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        private readonly ITableService tableService;

        public OrderController(IOrderService orderService, ITableService tableService)
        {
            this.orderService = orderService;
            this.tableService = tableService;
        }


        public IActionResult Index(string filter)
        {
            var items = orderService.GetAllOrdersWithDeleted();
            switch (filter)
            {
                case GlobalConstants.All:
                    return this.View(items);
                case GlobalConstants.Sent:
                    return this.View(items.Where(x => x.Status == GlobalConstants.Sent));
                case GlobalConstants.Open:
                    return this.View(items.Where(x => x.Status == GlobalConstants.Open));
                case GlobalConstants.Delivering:
                    return this.View(items.Where(x => x.Status == GlobalConstants.Delivering));
                case GlobalConstants.Delivered:
                    return this.View(items.Where(x => x.Status == GlobalConstants.Delivered));
                case GlobalConstants.Completed:
                    return this.View(items.Where(x => x.Status == GlobalConstants.Completed));
                case GlobalConstants.Deleted:
                    return this.View(items.Where(x => x.IsDeleted == true));
                default: return this.View(items);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await orderService.DeleteOrder(id);
                var table = tableService.GetTableByOrderId(id);
                if (table != null)
                {
                    tableService.MakeAvailable(table.Id);
                }

            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Boxty.Web/Controllers/ProductController.cs
namespace Boxty.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Boxty.Common;
    using Boxty.Services.Interfaces;
    using Boxty.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.Admin)]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IWebHostEnvironment environment;

        public ProductController(IProductService productService, ICategoryService categoryService, IWebHostEnvironment hostEnvironment)
        {
            this.categoryService = categoryService;
            this.environment = hostEnvironment;
            this.productService = productService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(productService.GetProducts<ProductViewModel>());
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var item = productService.GetProductById<ProductViewModel>(id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [Authorize(Roles = GlobalConstants.Admin)]
        public IActionResult Create()
        {
            var categories = categoryService.GetAllCategories<CategoryDropDownViewModel>();
            var viewModel = new ProductCreateInputModel
            {
                Categories = categories,
            };
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateInputModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = categoryService.GetAllCategories<CategoryDropDownViewModel>();
                return View(model);
            }

            try
            {
                await productService.AddProduct(model, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                model.Categories = categoryService.GetAllCategories<CategoryDropDownViewModel>();
                return this.View(model);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.Admin)]
        public IActionResult Edit(int id)
        {
            var product = productService.GetProductById<ProductEditInputModel>(id);
            product.Categories = categoryService.GetAllCategories<CategoryDropDownViewModel>();

            return View(product);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductEditInputModel input, int id)
        {
            if (!this.ModelState.IsValid)
            {
                input.Categories = categoryService.GetAllCategories<CategoryDropDownViewModel>();
                return this.View(input);
            }

            input.Id = id;
            await this.productService.UpdateAsync(input);
            return this.RedirectToAction(nameof(this.Details), new { input.Id });
        }


        [Authorize(Roles = GlobalConstants.Admin)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.productService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = GlobalConstants.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Boxty.Web/Controllers/TablesController.cs
namespace Boxty.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Boxty.Data;
    using Boxty.Models;
    using Boxty.Services.Interfaces;
    using Boxty.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [Authorize(Roles = "manager,admin")]
    public class TablesController : Controller
    {
        private readonly ITableService tableService;

        public TablesController(ITableService tableService)
        {
            this.tableService = tableService;
        }

        public IActionResult Index()
        {
            return View(tableService.GetTables<TableViewModel>());
        }

        public IActionResult Details(int id)
        {
            var table = tableService.GetTableById(id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Seats")] Table table)
        {
            if (ModelState.IsValid)
            {
                await tableService.CreateTable(table);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var table = tableService.GetTableById(id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.tableService.DeleteTable(id);
            return RedirectToAction(nameof(Index));
        }

        private bool TableExists(int id)
        {
            return tableService.GetAllTables().Any(e => e.Id == id);
        }
    }
}

Web/Boxty.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Boxty.Data.Models.BoxtyUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Boxty.Common.GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />


</head>
<body>
    <span class="AntiForge"> @Html.AntiForgeryToken() </span>
    <div id="wrapper" class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Boxty.Common.GlobalConstants.SystemName</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Menu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Create">Create Reservation</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (User.IsInRole(Boxty.Common.GlobalConstants.Admin))
                                {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Waiter" asp-controller="Waiter" asp-action="Index">Waiter Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="KitchenStaff" asp-controller="KitchenStaff" asp-action="Index">KitchenStaff</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Driver" asp-controller="Driver" asp-action="Index">Driver page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Tables</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Administration" asp-controller="Admins" asp-action="RolesList">Roles</a>
                                </li>
                            }
                            @if (User.IsInRole(Boxty.Common.GlobalConstants.Waiter))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Waiter" asp-controller="Waiter" asp-action="Index">Waiter Page</a>
                                </li>
                            }
                            @if (User.IsInRole(Boxty.Common.GlobalConstants.KitchenStaff))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="KitchenStaff" asp-controller="KitchenStaff" asp-action="Index">KitchenStaff Page</a>
                                </li>
                            }
                            @if (User.IsInRole(Boxty.Common.GlobalConstants.Driver))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Driver" asp-controller="Driver" asp-action="Index">Driver page</a>
                                </li>
                            }
                        }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>





        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - Boxty
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>