Web/Boxty.Web/Areas/Administration/Controllers/AdminsController.cs
namespace Boxty
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using AutoMapper;
    using Boxty.Common;
    using Boxty.Data.Models;
    using Boxty.Services.Interfaces;
    using Boxty.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.Admin)]
    [Area("Administration")]
    public class AdminsController : Controller
    {
        private readonly IAdminService adminService;
        private readonly RoleManager<ApplicationRole> roleManager;
        private readonly UserManager<BoxtyUser> userManager;

        public AdminsController( RoleManager<ApplicationRole> roleManager, UserManager<BoxtyUser> userManager, IAdminService adminService)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.adminService = adminService;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await adminService.CreateRole(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult RolesList()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = await adminService.GetUserRoles(role);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("RolesList");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = await adminService.EditUsersInRole(role);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                    {
                        return RedirectToAction("EditRole", new { Id = roleId });
                    }
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

Web/Boxty.Web/Controllers/UsersController.cs
namespace Boxty.Controllers
{
    using Boxty.Services;
    using Boxty.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    [Authorize]
    public class UsersController : Controller
    {
        public UsersController(IUserService userService)
        {
            UserService = userService;
        }

        protected IUserService UserService { get; }

        [HttpGet]
        public IActionResult UpdateShippingInfo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateShippingInfo(UpdateUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Users/UpdateShippingInfo");
            }

            await this.UserService.UpdateShippingInfo(model);

            return RedirectToAction("Checkout", "ShoppingCart"); // CheckoutComplete
        }
    }
}

Web/Boxty.Web/Areas/Administration/Views/Admins/CreateRole.cshtml
@model Boxty.Web.ViewModels.CreateRoleViewModel

@{
    ViewBag.Title = "Create New Role";
}

<form asp-action="CreateRole" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger">
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" placeholder="Name">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" style="width:auto">
                Create Role
            </button>
        </div>
    </div>
</form>

Web/Boxty.Web/Areas/Administration/Views/Admins/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h1>Edit Role</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="RolesList" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-controller="Admins" asp-action="EditUsersInrole" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto">Add Or Remove Users From Role</a>
        </div>
    </div>
</form>

Web/Boxty.Web/Areas/Administration/Views/Admins/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    ViewData["Title"] = "EditUsersInRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from this role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="EditRole" asp-route-id="@roleId"
               class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

Web/Boxty.Web/Areas/Administration/Views/Admins/RolesList.cshtml
@model IEnumerable<Boxty.Data.Models.ApplicationRole>

@{
    ViewBag.Title = "All Roles";
}

<h1>All Roles</h1>

@if (Model.Any())
{
    <a class="btn btn-primary mb-3" style="width:auto" asp-action="CreateRole"
       asp-controller="administration">Add new role</a>

    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a asp-controller="Admins" asp-action="EditRole"
                   asp-route-id="@role.Id" class="btn btn-primary">Edit
                </a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a role
            </h5>
            <a class="btn btn-primary" style="width:auto"
               asp-controller="admins" asp-action="CreateRole">
                Create Role
            </a>
        </div>
    </div>
}

Web/Boxty.Web/Areas/Administration/Views/Admins/UsersList.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<Boxty.Data.Models.BoxtyUser> UserManager
@inject Microsoft.AspNetCore.Identity.RoleManager<Boxty.Data.Models.ApplicationRole> RoleManager
@model IEnumerable<Boxty.ViewModels.OutputModels.UserOutputModel>

@{
    ViewBag.Title = "All Roles";
    var roles = RoleManager.Roles;
}
<head>
    <script src="~/js/site.js"></script>

</head>

<h1>All Users</h1>
<div class="row mt-5 col-md-3">
    <form id="myForm">
        <div class="form-row align-items-center">
            <div class="col-auto">
                <select class="custom-select mr-sm-2" id="mySelect" onchange="myFunction()">
                    <option selected>Select role...</option>
                    @foreach (var role in roles)
                    {
                        <option value="@role.Name">@role.Name</option>
                    }
                    <option value="All">All</option>
                </select>
            </div>
        </div>
    </form>
</div>
<h2></h2>
<p id="demo"></p>
<input type="text" id="mySearch" onkeyup="SearchFunc()" placeholder="Search by name...">
<table id="myMenu" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>UserName</th>
            <th>Name</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td class="text-center">@user.Id</td>
                <td class="text-center">@user.UserName</td>
                <td class="text-left">@string.Concat(user.FirstName, " ", user.LastName)</td>
                <td class="text-center">@user.Role</td>
                <td>
                    <div class="btn-group ">
                        <a class="btn btn-info" asp-controller="Users" asp-action="Profile" asp-route-userName="@user.UserName">Profile</a>
                    </div>
                    <div class="btn-group ">
                        <a class="btn btn-success" asp-controller="ShoppingCart" asp-action="RemoveFromCart" asp-route-productId="@user..Id">Done</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>